name: Build Data Grid

on:
  push:
    branches: ["main"]
    paths:
      - ""/data-grid/**""

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
      - run: pnpm install
        working-directory: ./data-grid
      - run: pnpm run build
        working-directory: ./data-grid
      - name: Upload to blob storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch --account-name blzaidg --auth-mode login -d '$web' -s ./data-grid/dist --overwrite --output none
      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
